Fetch remotes optionally and add args parsing

diff --git a/gsr b/gsr
--- a/gsr
+++ b/gsr
@@ -1,12 +1,13 @@
 #!/bin/bash
 
 if ((${BASH_VERSION%%.*} < 4)); then
-	echo "${0} requires Bash version 4 or later" >&2
+	echo "$(basename "$0") requires Bash version 4 or later" >&2
 	exit 1
 fi
 
 set -eu
 
+# Constants
 readonly SIGN_NONE=' '
 readonly SIGN_LOOSE='L'
 readonly SIGN_DIRTY='D'
@@ -15,8 +16,48 @@ readonly SIGN_BEHIND='B'
 readonly SIGN_AHEAD='A'
 readonly PORCELAIN_STATUS_LENGTH=6
 
+# Command options
+opt_fetch=false
+
+function throw_invalid_option() {
+	echo "$(basename "$0"): invalid option -- '$1'"
+	echo "Try '$(basename "$0") -h' for more information."
+	exit 2
+}
+
+function print_usage() {
+	cat <<EOM
+Usage: $(basename "$0") [OPTION]...
+
+    -f, --fetch
+        Fetch branches from remote repositories.
+    -h, --help
+        Lists usage instructions and available options.
+EOM
+}
+
+function parse_args() {
+	while [[ $# -gt 0 ]]; do
+		case "$1" in
+		-f | --fetch)
+			opt_fetch=true
+			shift
+			;;
+		-h | --help)
+			print_usage
+			exit 3
+			;;
+		--)
+			shift
+			break
+			;;
+		*) throw_invalid_option "$@" ;;
+		esac
+	done
+}
+
 function check_status() {
-	local repo="${1}"
+	local repo="$1"
 	local porcelain=()
 	local local_branch=''
 	local remote_branch=''
@@ -32,8 +73,10 @@ function check_status() {
 	fi
 
 	# Remote unavailable
-	if ! git fetch --quiet &>/dev/null; then
-		porcelain+=("${SIGN_REMOTE_UNAVAILABLE}")
+	if ${opt_fetch}; then
+		if ! git fetch --quiet &>/dev/null; then
+			porcelain+=("${SIGN_REMOTE_UNAVAILABLE}")
+		fi
 	fi
 
 	local_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
@@ -56,7 +99,7 @@ function check_status() {
 }
 
 function check_branch() {
-	local repo="${1}"
+	local repo="$1"
 	local local_branch=''
 
 	local_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
@@ -80,6 +123,8 @@ function should_use_colors() {
 }
 
 function main() {
+	parse_args "$@"
+
 	# Map (repo => porcelain) and (repo => branch)
 	declare -A statuses
 	declare -A branches
@@ -117,4 +162,4 @@ function main() {
 	done
 }
 
-main
+main "$@"
